appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IASswok/nE5IdTVzbedC4pv09d79bsa8Bv+PiPM/zLLKyMVKpUpSUaTnW2i9pjoqgSnZNiRQMIBIS9XTOhsm8NrU721MVvSW1kB7+kC9C0z7rPgan+DzlciyudO4PJb4UDtZRQ2j4TJB1mbl79RrJLWcwA7PLtYJVKrAzAr9va0oKfzin9oq+AD4Xk0hJ58HxSZrDYTthCL/1pZ7vSBezFO1cpT3wlkMXO52JJLcxAEX+vDFv4D251Ho9trSju1iiIx/m5CcX8efv4I2x/KSMDgnfTih/WWWBRTTiLw4H9ZyLCFWPpZIis5kApl1uO4FQwf9GvQds9mGBpmn9dfx6yrwlUQxIhKuUgQMZuL9v8Rv4Tnrqy/ikdRiJGlwD1geyNIlMYJ7QTxtWgw1YTiv1+xvw2jJB0xv1MxtLGkVXyJHTB7VE7Q29CRX4AyGJbkUVx91OJUw0p9LvfvVQ+g6gE3w1ycGTduR955Joc64nd3DXT7ZBxPS7BrB1pw2vwZZ9pqTtMFB3FgBEOnh9Lyi5r7C5iYPSCQJIgD4EDQLH4p86GYXMIaPzYw8dl2Jyj12Q9J2pOElX2x4icS4gSUiCnG6GhOCubwGK4CR1Gf7y6QN/dTRsQYUvNjz/K4bgH6GEilEOJL4VX/BdMubV+B9tON6bdjSMDcSEzFImspLzLE=
